Compile resources in subdirectories correctly.
Makman2/GCR_CMake pull request #5
Opened 2016-10-15 19:10 UTC by 9fcc

Those changes allows this project to be in a subdirectory (with add_subdirectory) of main project that uses it.

2016-10-15 19:39 UTC, Makman2 commented
@9fcc hey :D
wow cool someone has seen my GCR_CMake extensions I've used only privately for a single project, that is *ugh* currently not in active development :3

Thanks for submitting the PR! :D Changes look good, some minor stuff I would ask you to change (via `git commit --amend`, see inline comments), then I would merge that directly and make a new release :)

2016-10-15 19:44 UTC, Makman2 requested changes

2016-10-15 19:44 UTC, Makman2 commented on README.md
>  - **SOURCE_DIR** ***resource_directory***
commit message:
could you remove the trailing period? :)
( I know this is a bit nit-picky, but I'm currently working on https://github.com/coala/coala which is all about code quality, involving good commit messages :3)

2016-10-15 19:44 UTC, Makman2 commented on macros/CompileGResources.cmake
> +    #           or CMAKE_CURRENT_SOURCE_DIR (if SOURCE_DIR is not overriden),
could you put `this` here?

2016-10-15 19:44 UTC, Makman2 commented on macros/GenerateGXML.cmake
> +    #           or CMAKE_CURRENT_SOURCE_DIR (if SOURCE_DIR is not overriden),
here too :)

2016-10-15 20:40 UTC, Makman2 commented
If you don't want to fixup the stuff I've mentioned, I can take over for you, making a new PR and modifying your commit (don't fear, the author information is kept :D)

2016-10-16 15:32 UTC, andr-dots commented on README.md
>  - **SOURCE_DIR** ***resource_directory***
Done.

2016-10-17 18:45 UTC, merged

2016-10-17 18:46 UTC, Makman2 commented
@9fcc many thanks!! :D I really appreciate this PR :) Haven't imagined someone would stumble upon these macros :)

2016-10-18 17:51 UTC, 9fcc commented
Well, we used those macros for a long time in our project and they saved some my time. It goes as a submodule in git in a subdirectory so original version wasn't perfect. At the moment we decided to push changes back to original developer. If GTK+ someday would become popular those macros would be very useful. Thanks.